package com.example.myapplication

// The 100 most common words in Chinese speech, I had AI generate the list, I modified the phonetic
// attribute to help the text to speech pronounce more correctly, there are still some elusive sounds.
object WordData {
    val basicWords = listOf(
        WordItem("wǒ", "我", "I", "whoah"),
        WordItem("nǐ", "你", "you","knee"),
        WordItem("shì", "是", "to be","shih"),
        WordItem("tā", "他", "he","tah"),
        WordItem("wǒmen", "我们", "we","whoah-men"),
        WordItem("bù", "不", "not","boo"),
        WordItem("zhè", "这", "this","jeh"),
        WordItem("hǎo", "好", "good","how"),
        WordItem("shénme", "什么", "what","shen-meh"),
        WordItem("jiù", "就", "just","joe"),
        WordItem("yǒu", "有", "to have","yo"),
        WordItem("tā", "她", "she","tah"),
        WordItem("yào", "要", "to want", "yow"),
        WordItem("shuō", "说", "to say","shwo"),
        WordItem("zhīdào", "知道", "to know","gee-dow"),
        WordItem("dōu", "都", "all","dough"),
        WordItem("huì", "会", "can","hui"),
        WordItem("qù", "去", "to go","chee"),
        WordItem("rén", "人", "person","ren"),
        WordItem("nà", "那", "that","nah"),
        WordItem("yě", "也", "also","yeh"),
        WordItem("tāmen", "他们", "they","tah-men"),
        WordItem("xiǎng", "想", "to think","song"),
        WordItem("lái", "来", "to come","lye"),
        WordItem("zuò", "做", "to do","zwo"),
        WordItem("yígè", "一个", "one (measure)","yee-ga"),
        WordItem("méiyǒu", "没有", "not have","may-yo"),
        WordItem("ràng", "让", "to let","wrong"),
        WordItem("hěn", "很", "very","hen"),
        WordItem("néng", "能", "can","nong"),
        WordItem("nǐmen", "你们", "you (plural)","knee-men"),
        WordItem("hái", "还", "still","hi"),
        WordItem("zhège", "这个", "this one","jeh-ga"),
        WordItem("zěnme", "怎么", "how","zen-meh"),
        WordItem("diǎn", "点", "o’clock / point","dawn"),
        WordItem("zhèxiē", "这些", "these","je-sea"),
        WordItem("wǒde", "我的", "my","wa-duh"),
        WordItem("dào", "到", "to arrive","dow"),
        WordItem("gěi", "给", "to give","gay"),
        WordItem("mén", "门", "door","men"),
        WordItem("shúi", "谁", "who","shway"),
        WordItem("zhī", "之", "of (classical)","gee"),
        WordItem("nǎr", "哪儿", "where","nawr"),
        WordItem("kàn", "看", "to look","con"),
        WordItem("xiǎngyào", "想要", "to want","song-yow"),
        WordItem("shū", "书", "book","shoe"),
        WordItem("diànnǎo", "电脑", "computer","dan-now"),
        WordItem("chī", "吃", "to eat","chee"),
        WordItem("hē", "喝", "to drink","heh"),
        WordItem("xuéxiào", "学校", "school","su-sow"),
        WordItem("zhōng", "中", "middle","jong"),
        WordItem("jiā", "家", "home","jah"),
        WordItem("tiān", "天", "sky / day","tan"),
        WordItem("yī", "一", "one","yee"),
        WordItem("èr", "二", "two","air"),
        WordItem("sān", "三", "three","sawn"),
        WordItem("zài", "在", "at","tsai"),
        WordItem("nán", "难", "difficult","naan"),
        WordItem("yīnggāi", "应该", "should","ying-guy"),
        WordItem("kěyǐ", "可以", "can","ke-yee"),
        WordItem("xiǎo", "小", "small","sow"),
        WordItem("dà", "大", "big","daw"),
        WordItem("shéi", "谁", "who","shay"),
        WordItem("zhǎo", "找", "to search","chao"),
        WordItem("máng", "忙", "busy","mong"),
        WordItem("cuò", "错", "wrong","cho"),
        WordItem("yìsi", "意思", "meaning","yee-sa"),
        WordItem("duì", "对", "correct","duay"),
        WordItem("bāngzhù", "帮助", "to help","bong-shu"),
        WordItem("rènshi", "认识", "to know (people)","ren-shih"),
        WordItem("xīngqī", "星期", "week","sin-chee"),
        WordItem("gēn", "跟", "with","gen"),
        WordItem("xièxie", "谢谢", "thanks","see-see"),
        WordItem("duìbuqǐ", "对不起", "sorry","duay-boo-chee"),
        WordItem("méiguānxi", "没关系", "it’s okay","may-gwan-see"),
        WordItem("qián", "钱", "money","chan"),
        WordItem("yòng", "用", "to use","yong"),
        WordItem("zhǐ", "只", "only","chee"),
        WordItem("yīnwèi", "因为", "because","yeen-way"),
        WordItem("suǒyǐ", "所以", "so","so-yee"),
    )
}